@base_url = http://127.0.0.1:8000/api
@arthur_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzY2NDEzMDUxLCJpYXQiOjE3NjYxNTM4NTF9.QcyuX11Fw8DlCOgxDKsrxIn8skc5QiIlzOROOggwe3o

### Join Mission
# @prompt mission_id
POST {{base_url}}/crew/join/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}

### Leave Mission
# @prompt mission_id
DELETE {{base_url}}/crew/leave/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}
