@base_url = http://127.0.0.1:8000/api
@arthur_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiZXhwIjoxNzY2ODQ4NDU4LCJpYXQiOjE3NjY1ODkyNTh9.qri9WQ--YmbmyWOpnEOLYxJfYUXECiDQmS-0HopQ5OE

### Join Mission
# @prompt mission_id
POST {{base_url}}/crew/join/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}

### Leave Mission
# @prompt mission_id
DELETE {{base_url}}/crew/leave/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}
