@base_url = http://127.0.0.1:8000/api
@arthur_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzY2NDEzMDUxLCJpYXQiOjE3NjYxNTM4NTF9.QcyuX11Fw8DlCOgxDKsrxIn8skc5QiIlzOROOggwe3o

### create new mission
# @prompt mission_name Mission Name
# @prompt description Mission Description
POST {{base_url}}/mission-management
Content-Type: application/json
Authorization: Bearer {{arthur_token}}


{
    "name": "{{mission_name}}",
    "description":"{{description}}"
}


### update mission
# @prompt mission_id Mission ID
# @prompt mission_name Mission Name
# @prompt description Mission Description
PATCH {{base_url}}/mission-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}


{
    "name": "{{mission_name}}",
    "description": "{{description}}"
}


### remove mission
# @prompt mission_id Mission ID
DELETE {{base_url}}/mission-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{arthur_token}}
